# Generated by Django 2.2.6 on 2019-10-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'House', 'verbose_name_plural': 'Houses'},
        ),
    ]
