# Generated by Django 2.2.6 on 2019-10-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image_prop',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
