# Generated by Django 2.2.6 on 2019-10-17 03:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191015_1738'),
        ('house', '0006_house_image_prop'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_house',
            name='article',
            field=models.ForeignKey(blank=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='article_info', to='blog.Article'),
            preserve_default=False,
        ),
    ]
