# Generated by Django 2.2.6 on 2019-10-17 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20191017_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_house',
            name='article',
        ),
    ]
